<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-TKF8PN85" failures="2" tests="2" name="Test" time="100.753" errors="0" timestamp="2024-11-06T14:31:51 EST">
  <testcase classname="tests.LoginTest" name="login" time="15.698">
    <failure type="java.lang.AssertionError" message="expected [Sucessfull] but found [Failure]">
      <![CDATA[java.lang.AssertionError: expected [Sucessfull] but found [Failure]
at tests.LoginTest.login(LoginTest.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="tests.LoginTest" name="login" time="14.903">
    <failure type="java.lang.AssertionError" message="expected [failure] but found [Failure]">
      <![CDATA[java.lang.AssertionError: expected [failure] but found [Failure]
at tests.LoginTest.login(LoginTest.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Test -->
